apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000  # Specify a port number between 30000 and 32767
  selector:
    app: server
