name: Deploy to AWS

on:
  push:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  pull_request:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  workflow_dispatch:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'

jobs:
  create-ecr-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: |
          echo "aws_access_key = \"AKIA4LD7OFQOTO5ZFSEU\"" > terraform/terraform.tfvars
          echo "aws_secret_access_key = \"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\"" >> terraform/terraform.tfvars

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform init
          terraform plan

      # - name: Check if ECR repository exists
      #   id: check-ecr
      #   run: |
      #     REPO_NAME="flask-react-app-repo-ecr"
      #     REPO_EXISTS=$(aws ecr describe-repositories --repository-names $REPO_NAME --query 'repositories[0]' --output text)
      #     echo "::set-output name=repo_exists::${REPO_EXISTS}"

      - name: Terraform Apply for ECR
        if: steps.check-ecr.outputs.repo_exists == 'null'
        working-directory: terraform
        run: terraform apply -auto-approve -var="create_ecr_repository=true"

  build-and-push:
    needs: create-ecr-repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 848523308061.dkr.ecr.us-east-1.amazonaws.com
          registry-type: public
        env:
          AWS_REGION: us-east-1
          TERRAFORM_CLI_PATH: /home/runner/work/_temp/40094850-0c19-468c-a023-49736052691c

      - name: Build and Push Docker image
        id: build-image
        env:
          ECR_REGISTRY: 848523308061.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: flask-react-app-repo-ecr
          IMAGE_TAG: latest
        run: |
          cd server
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  apply-remaining-resources:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: |
          echo "aws_access_key = \"AKIA4LD7OFQOTO5ZFSEU\"" > terraform/terraform.tfvars
          echo "aws_secret_access_key = \"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\"" >> terraform/terraform.tfvars

      - name: Terraform Apply for remaining resources
        working-directory: terraform
        run: terraform apply -auto-approve
