name: Deploy to AWS

on:
  push:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  pull_request:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  workflow_dispatch:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: |
          echo "aws_access_key = ${{ secrets.AWS_ACCESS_KEY }}" 
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" 

      - name: Terraform Plan
        run: |
          terraform init
          terraform plan
