name: Deploy with Terraform

on:
  push:
    branches:
      - aws
    paths:
      - 'terraform/main.tf'
  pull_request:
    branches:
      - aws
    paths:
      - 'terraform/main.tf'
  workflow_dispatch:
    branches:
      - aws
    paths:
      - 'terraform/main.tf'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
