name: Deploy to AWS

on:
  push:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  pull_request:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'
  workflow_dispatch:
    branches:
      - aws
    paths:
      - 'server/Dockerfile'
      - 'server/app.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: |
          echo "aws_access_key = \"AKIA4LD7OFQOTO5ZFSEU\"" > terraform/terraform.tfvars
          echo "aws_secret_access_key = \"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\"" >> terraform/terraform.tfvars

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform init
          terraform plan
      
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
