name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - compose

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          docker-compose up -d --build

      - name: Print Server IP
        run: ifconfig enp0s3 | awk '/inet / {print $2}' | head -n 1

      - name: Wait for Container to Start
        run: sleep 10

      - name: Print Server Logs
        run: docker-compose logs flask-react-app_server