name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v1.2.0
        with:
          compose-file: |
            docker-compose.yml

      - name: Build and Deploy
        run: |
          docker-compose up -d --build

      - name: Wait for server to start
        run: |
          echo "Waiting for server to start..."
          until curl --output /dev/null --silent --head --fail "http://localhost:5000"; do sleep 5; done

      - name: Verify Deployment
        run: curl -sSf "http://localhost:5000/api/message"
