on:
  push:
    branches:
      - compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update system packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Docker dependencies
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      - name: Add Docker GPG key
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

      - name: Add Docker repository
        run: |
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Update system packages (again)
        run: |
          sudo apt-get update

      - name: Install Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build and Deploy
        run: |
          docker compose down --rmi all
          docker compose up -d --build
          
      - name: Verify Server Deployment
        run: curl http://localhost:5000/api/message
      
      - name: Verify Client Deployment
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do sleep 5; done