name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          REACT_APP_SERVER_IP: <IP_OF_SERVER>
        run: npm run build

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            docker-compose.yml

      - name: Build and Deploy
        run: |
          docker-compose up -d --build

      - name: Verify Server Deployment
        run: curl http://$SERVER_IP:5000/api/message
      
      - name: Verify Client Deployment
        run: |
          until curl --output /dev/null --silent --head --fail http://$SERVER_IP:3000; do sleep 5; done
