name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - compose

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          docker-compose up -d --build

      - name: Print Docker Images
        run: docker images
