name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - compose

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          docker-compose up -d --build

      - name: Verify Server Deployment
        run: curl -sSf "http://localhost:5000/api/message"

      - name: Verify Client Deployment
        run: |
          until curl -sSf --output /dev/null "http://localhost:3000"; do sleep 5; done