name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy AWS Infrastructure'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: |
          echo "aws_access_key = \"AKIA4LD7OFQOTO5ZFSEU\"" > terraform/terraform.tfvars
          echo "aws_secret_access_key = \"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\"" >> terraform/terraform.tfvars

      - name: Terraform Destroy
        working-directory: terraform
        run: |
          terraform init
          terraform destroy -auto-approve