name: Apply s3 cloudfront Infrastructure
on:
  workflow_dispatch:
  push:
    branches:
      - aws
    paths:
      - 'apply_to_S3_Cloudfront.txt'
      
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    env:
      REGION: us-east-1
      TF_WORKSPACE: default
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.9

    - name: Terraform Init
      working-directory: terraform
      run: apply_s3_cloudfront init

    - name: Terraform Apply
      working-directory: terraform
      run: apply_s3_cloudfront apply -auto-approve
